version: '3'

services:

  reverse-proxy:
    image: nginx
    container_name: nginx_reverse_proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  web1:
    image: httpd:latest
    container_name: apache_webserver_1
    volumes:
      - ./web1:/usr/local/apache2/htdocs/
    ports:
      - 8080:80
  web2:
    image: httpd:latest
    container_name: apache_webserver_2
    volumes:
      - ./web2:/usr/local/apache2/htdocs/
    ports:
      - 8081:80
  web3:
    image: httpd:latest
    container_name: apache_webserver_3_1
    volumes:
      - ./web3:/usr/local/apache2/htdocs/
    ports:
      - 8082:80
  web3load:
    image: httpd:latest
    container_name: apache_webserver_3_2
    volumes:
      - ./web3load:/usr/local/apache2/htdocs/
    ports:
    - 8083:80
